### ISSUE TITLE
IO one by one addons conflict

### ISSUE THREAD

**Issue by AH349** [AnKing-VIP/AnKing-Note-Types#107]
Anking IO one by one

When using the IO one-by-one template I get the image without any cloze deletions. After enabling and disabling add-ons I’ve narrowed it to a conflict with these 2 add-ons: 

Edit Field During Review Cloze 
Picmonic Anki Add-on 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X ] I've restarted Anki to see if it helps
 - [X ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [X ] I've tried to disable add-ons to see if there are any interactions present
 - [X ] My issue disappears when I hold shift while starting Anki.
 - [X ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using? 

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.55Q6
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
Windows 10

*Please include OS version as well if possible*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Can you include a picture or video?

**Comment by AH349** [comment]
Hope these help :) whenever either of these 2 addons are enabled the IO 1:1 isn't working. Whenever they are disabled it works fine. Thanks!

![Edit field during review cloze - problem](https://user-images.githubusercontent.com/99471389/212258773-a0eaa229-1932-40c7-bc4d-0fc8bbc8ee98.png)
![IO 1-1 working good](https://user-images.githubusercontent.com/99471389/212258841-74107cbe-1171-4a73-9848-1fca67a991e9.png)
![Picmonic add on problem](https://user-images.githubusercontent.com/99471389/212258903-34387b93-1559-44fa-9ae9-9f8a88586efb.png)

**Comment by AnKingMed** [comment]
I'm having trouble even loading Anki with the Picmonic add-on so I'm guessing it's that. The Edit Field During Review Cloze add-on is working fine on mine
