### ISSUE TITLE
Question and Answer in the Text Field which is Read by TTS is displayed twice in Ankidroid. if TTS is enabled.

### ISSUE THREAD

**Issue by fredjoe7** [AnKing-VIP/AnKing-Note-Types#126]
Actually all note types that i used via anking note type addon reproduced the issue.

#### Problem description

I enabled text to speech option in all anking notes using the anking note type add on,
it is fantastic. i use it more often in the windows laptop.
The problem was when i opened Ankidroid to review cards in my mobile.
the Text Field with the question and answer which TTS is supposed to read appears twice in my mobile review.
inititally i thought there is some duplicates in the styling or css codes and couldn't find anything.
The problem resolved when i Turned of TTS in my Anki windows using anking note type addon  and synced it.

so now everytime i want to review in mobile i want to either turn off the TTS option in anking note type addon or change the card css or else will be stuck reviewing with question and answers displayed twice.

otherwise the anking note addon is powerful and i really enjoy using it. 

thank you

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.61 (0c1eaf4c)⁩
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

"Windows 11"

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Have you reported this to AnkiDroid? I suspect it’s an issue on their end

**Comment by fredjoe7** [comment]
No.

**Comment by fredjoe7** [comment]
OK

**Comment by fredjoe7** [comment]
after the update of ankidroid this problem is resolved

**Comment by fredjoe7** [comment]
actually enabling the v3 scheduler in ankidroid seems to stop displaying the content twice
