### ISSUE TITLE
Due count on back of card for Anking Overhaul notes with "flip to back of card automatically" feature

### ISSUE THREAD

**Issue by Monchi33** [AnKing-VIP/AnKing-Note-Types#128]
Asking Overhaul

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```

#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*

#### Problem case

*Is your feature request related to a problem? If so, please describe it here.  E.g.: "My workflow is such and such, and this and that would help."* 

#### Solution

*Concisely describe the solution you would like*

*Concisely describe alternatives you've considered (if any)*

#### More information

*Additional context: Add any other context or screenshots about the feature request here.*

**Comment by AnKingMed** [comment]
I'm sorry I don't quite understand what you're suggesting. Can you explain a bit more?
