### ISSUE TITLE
I keep having to click "Update notetypes" in 'General' tab 

### ISSUE THREAD

**Issue by shmuelsash** [AnKing-VIP/AnKing-Note-Types#133]
#### Which Note Type (and version) is this about?
General (updated addon on 4/27)

#### Problem description
Each time I open Anki I get a notification that there is an update so I open the dialog and click update. It says it will cause a full sync, I click yes, and it does its thing. However, when I start anki the next time I have to do the same thing again. 

#### Checklist

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 
#### What Anki version are you using?
```
Version ⁨2.1.61 (0c1eaf4c)⁩
Python 3.9.15 Qt 6.4.2 PyQt 6.4.0
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Windows 11 22H2; build 22621.1635

**Comment by shmuelsash** [comment]
I disabled all the addons I have and it fixes the issue but when I reenable all the addons again, although I don't get the pop-up that there is an update, when I go into the settings the "Update notetypes" button is clickable again

Here are my enabled addons
![image](https://user-images.githubusercontent.com/35056305/234838505-001cb19a-1d61-4fb1-a9dc-a4e3fd72c2f4.png)
****

**Comment by AnKingMed** [comment]
@RisingOrange could this be due to your last update?

**Comment by RisingOrange** [comment]
Probably, I'm looking into it.

**Comment by shmuelsash** [comment]
I've been having this issue for a really long time now but the last update made the pop up window so i wasn't able to ignore it.

Now (after disabling all the addons and updating the note types) I've got it back to the point where it was how it has been for the past while where I still can click to update if I go into the settings of the addon but I'm not getting any pop up window

This is what I see in the general tab
![image](https://user-images.githubusercontent.com/35056305/234848525-d57e62a6-2b29-4921-974b-a5efad0132c5.png)

**Comment by shmuelsash** [comment]
Nevermind

The pop up is back again 🙈

**Comment by shmuelsash** [comment]
One thing I just noticed is that when I click to update the notetype I lose all my customization settings for the AnkingOverhaul notetype

**Comment by RisingOrange** [comment]
@shmuelsash Can you try to open Anki's debug console, paste the code below, press `Ctrl+Enter` and then send the result here?
Here are the instructions for opening the debug console: https://docs.ankiweb.net/misc.html

```python
from importlib import import_module
addon = import_module("952691989")
config_window = addon.gui.config_window.NotetypesConfigWindow
models_with_updates = config_window.models_with_available_updates()
model_names = [
    model["name"] for model in models_with_updates
]
print(model_names)
```

**Comment by RisingOrange** [comment]
This will tell us which note types have updates available according to the add-on.

**Comment by RisingOrange** [comment]
Thanks! Please do the same for this script:

```python
from importlib import import_module
addon = import_module("952691989")
config_window = addon.gui.config_window.NotetypesConfigWindow
models_with_updates = config_window.models_with_available_updates()
model_names = [
    model["name"] for model in models_with_updates
]
print(model_names)

model_versions = []
for model in models_with_updates:
    model_versions.append(config_window.model_version(model))

print(model_versions)
```

This does the same as the previous one, but it also provides the version information of the installed note types.

**Comment by shmuelsash** [comment]
>>> from importlib import import_module
... addon = import_module("952691989")
... config_window = addon.gui.config_window.NotetypesConfigWindow
... models_with_updates = config_window.models_with_available_updates()
... model_names = [
...     model["name"] for model in models_with_updates
... ]
... print(model_names)
... 
... model_versions = []
... for model in models_with_updates:
...     model_versions.append(config_window.model_version(model))
... 
... print(model_versions)
... 
... print(config_window._all_supported_note_types())
['AnKing', 'AnKingOverhaul', 'AnKingOverhaul (AnKing / AnKingMed)', 'IO-one by one', 'IO-one by one (AnKing / AnKingMed)']
[None, None, None, None, None]
['AnKing', 'AnKingOverhaul', 'AnKingOverhaul (AnKing / AnKingMed)', 'IO-one by one', 'IO-one by one (AnKing / AnKingMed)']

**Comment by RisingOrange** [comment]
This script will print the beginning of the `AnKing` front card template:
```python
anking_template_start = '\n'.join(mw.col.models.by_name("AnKing")["tmpls"][0]["qfmt"].split("\n")[:10])
print(anking_template_start)
```

**Explanation**
It seems that the add-on thinks that all the AnKing note types you are using need updates. 
The add-on determines if a note type needs an update by comparing the note type version that is specified on the top of the card template with the newest available one. In your case the add-on does not find this version information on your card templates.

It should look like this, but it will probably look different for you:
```
<!-- version cf1a371 -->
<div id="text">{{cloze:Text}}</div>

<br>

<!-- ##############  Text-to-speech  ##############
replace the arrows/dashes from the statement below with double curly brackets-->

<!--tts en_US voices=Apple_Samantha,Microsoft_Zira speed=1.4:cloze:Text-->
```

It's weird that updating the note type seems to have no effect. I think this might be due to an interaction with a different add-on.

**Comment by shmuelsash** [comment]
>>> anking_template_start = '\n'.join(mw.col.models.by_name("AnKing")["tmpls"][0]["qfmt"].split("\n")[:10])
... print(anking_template_start)
<script src="_remainingtime.min.js"></script>


<div id="text">{{cloze:Text}}</div>

<br>

**Comment by shmuelsash** [comment]
With the addon disabled I got this

--
>>> anking_template_start = '\n'.join(mw.col.models.by_name("AnKing")["tmpls"][0]["qfmt"].split("\n")[:10])
... print(anking_template_start)
<script src="_remainingtime.min.js"></script>


<div id="text">{{cloze:Text}}</div>

<br>



--

**Comment by shmuelsash** [comment]
Seems to be working now, but I lost all my customizations again

Is that supposed to happen?

**Comment by shmuelsash** [comment]
Its weird when I run this I still get 
```
>>> >>> anking_template_start = '\n'.join(mw.col.models.by_name("AnKing")["tmpls"][0]["qfmt"].split("\n")[:10])
... ... print(anking_template_start)
... <!-- # 2eecab49dc1f9618 --><script src="_remainingtime.min.js"></script><!-- / 2eecab49dc1f9618 -->
... 
... <!-- version cf1a371 -->
... <div id="text">{{cloze:Text}}</div>
... 
... <br>
... 
... <!-- ##############  Text-to-speech  ##############
... replace the arrows/dashes from the statement below with double curly brackets-->
Traceback (most recent call last):
  File "aqt.debug_console", line 292, in onDebugRet
  File "<string>", line 1
    >>> anking_template_start = '\n'.join(mw.col.models.by_name("AnKing")["tmpls"][0]["qfmt"].split("\n")[:10])
    ^
SyntaxError: invalid syntax
```

> This script will print the beginning of the `AnKing` note type front card template:
> 
> ```python
> anking_template_start = '\n'.join(mw.col.models.by_name("AnKing")["tmpls"][0]["qfmt"].split("\n")[:10])
> print(anking_template_start)
> ```
> 
> **Explanation** It seems that the add-on thinks that all the AnKing note types you are using need updates. The add-on determines if a note type needs an update by comparing the note type version that is specified on the top of the card template with the newest available one. In your case the add-on does not find this version information on your card templates.
> 
> It should look like this, but it will probably look different for you:
> 
> ```
> 
> <div id="text">{{cloze:Text}}</div>
> 
> <br>
> 
> 
> 
> 
> ```
> 
> Note the version information in the first line.
> 
> It's weird that updating the note type seems to have no effect on the version information on the note type. I think this might be due to an interaction with a different add-on.



> This script will print the beginning of the `AnKing` note type front card template:
> 
> ```python
> anking_template_start = '\n'.join(mw.col.models.by_name("AnKing")["tmpls"][0]["qfmt"].split("\n")[:10])
> print(anking_template_start)
> ```
> 
> **Explanation** It seems that the add-on thinks that all the AnKing note types you are using need updates. The add-on determines if a note type needs an update by comparing the note type version that is specified on the top of the card template with the newest available one. In your case the add-on does not find this version information on your card templates.
> 
> It should look like this, but it will probably look different for you:
> 
> ```
> 
> <div id="text">{{cloze:Text}}</div>
> 
> <br>
> 
> 
> 
> 
> ```
> 
> Note the version information in the first line.
> 
> It's weird that updating the note type seems to have no effect on the version information on the note type. I think this might be due to an interaction with a different add-on.

**Comment by RisingOrange** [comment]
The customizations should be kept between updates. I think that if you disabled the other add-on and there was another update to the note types, the customizations would not go away.

**Comment by RisingOrange** [comment]
Great! 

I'll see if I can make the AnKing note types add-on work together with this add-on, but this might take some time.

**Comment by shmuelsash** [comment]
Tysm I really appreciate your help!!
