### ISSUE TITLE
Autoopen not working on Ankidroid

### ISSUE THREAD

**Issue by shmuelsash** [AnKing-VIP/AnKing-Note-Types#134]
#### Which Note Type (and version) is this about?
AnKingOverhaul (updated addon on 4/27)

#### Problem description
Autoopen works perfectly on desktop but not on mobile (android)

#### Checklist
 - [X] I've restarted Anki to see if it helps
 - [X] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [X] I've tried to disable add-ons to see if there are any interactions present
 - [X] My issue disappears when I hold shift while starting Anki.
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
```
Version ⁨2.1.61 (0c1eaf4c)⁩
Python 3.9.15 Qt 6.4.2 PyQt 6.4.0

Ankidroid 2.15.6
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Windows 11 22H2; build 22621.1635
Android 13

**Comment by shmuelsash** [comment]
Sorry I'm having so many issues today 😆

**Comment by fredjoe7** [comment]
i have the same issue.
