### ISSUE TITLE
Getting this issue upon opening my Anki

### ISSUE THREAD

**Issue by mkrivichkin** [AnKing-VIP/AnKing-Note-Types#136]
This is the error message that pops up whenever I open Anki:

Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you’ve discovered the add-on that is causing the problem, please report the issue to the add-on author.
Debug info:
Anki 2.1.54 (b6a7760c) Python 3.9.7 Qt 6.3.1 PyQt 6.3.1
Platform: Mac 11.6.5
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2023-04-29 00:50:35
Add-ons possibly involved: ⁨AnKing Note Types Easy Customization⁩

Caught exception:
Traceback (most recent call last):
File “aqt.progress”, line 118, in handler
File “aqt.main”, line 197, in on_window_init
File “aqt.main”, line 290, in setupProfile
File “aqt.main”, line 470, in loadProfile
File “aqt.hooks_gen”, line 3244, in call
File “/Users/mkriv/Library/Application Support/Anki2/addons21/952691989/init.py”, line 36, in on_profile_did_open
maybe_show_notetypes_update_notice()
File “/Users/mkriv/Library/Application Support/Anki2/addons21/952691989/init.py”, line 63, in maybe_show_notetypes_update_notice
models_with_updates = models_with_available_updates()
File “/Users/mkriv/Library/Application Support/Anki2/addons21/952691989/gui/config_window.py”, line 558, in models_with_available_updates
return [
File “/Users/mkriv/Library/Application Support/Anki2/addons21/952691989/gui/config_window.py”, line 562, in
if _new_version_available_for_model(model)
File “/Users/mkriv/Library/Application Support/Anki2/addons21/952691989/gui/config_window.py”, line 569, in _new_version_available_for_model
newest_version = note_type_version(anking_notetype_model(base_name))
File “/Users/mkriv/Library/Application Support/Anki2/addons21/952691989/notetype_setting_definitions.py”, line 595, in anking_notetype_model
(ANKING_NOTETYPES_PATH / notetype_name / f"{notetype_name}.json").read_text()
TypeError: unsupported operand type(s) for /: ‘PosixPath’ and ‘NoneType’

**Comment by AnKingMed** [comment]
Can you try deleting the anking note types addon and then re-download it?

**Comment by mkrivichkin** [comment]
Is this going to affect my flashcards?

**Comment by AnKingMed** [comment]
No that shouldn't.

**Comment by nutellakings** [comment]
Having the same issue. I tried redownloading the add-on, making sure I have the newest Anki app.

**Comment by AnKingMed** [comment]
@nutellakings did you delete the addon and re-download?

**Comment by RisingOrange** [comment]
@nutellakings If re-installing doesn't fix the issue can you open Anki's debug console, paste the code below, press `Ctrl+Enter` and then send the result here?
Here are the instructions for opening the debug console: https://docs.ankiweb.net/misc.html
The resulting information will help me to fix the problem.

```python
from pprint import pformat
from importlib import import_module
addon = import_module("952691989")
config_window = addon.gui.config_window

version_name_to_base_name = {}
for name in config_window._names_of_all_supported_note_types():
  version_name_to_base_name[name] = config_window._model_base_name(name)
  
print(f"Installed AnKing note types: {config_window._names_of_all_supported_note_types()}")
print(f"Note type name to note type base name:\n{pformat(version_name_to_base_name)}")
```
