### ISSUE TITLE
Anki iOS Hint Button Size

### ISSUE THREAD

**Issue by sugarycat** [AnKing-VIP/AnKing-Note-Types#138]
Hello,

The field buttons (e.g. First Aid, Lecture Notes, etc) are quite small on my Anki iOS app, and I was wondering how I can adjust the Anking Overhaul styling CSS to increase the button sizes on the app.

Thank you!

EDIT: the title says Hint Button Size, but I meant to say **field** button size

**Comment by AnKingMed** [comment]
You could try changing this code in the styling:
```
.mobile .button-general {
  font-size: 18px;
  padding: 9px 7px;
}
```
