### ISSUE TITLE
Can't bind arrow keys to reveal cloze one by one

### ISSUE THREAD

**Issue by aly-k** [AnKing-VIP/AnKing-Note-Types#141]
### Which Note Type (and version) is this about?
Anking overhaul version 3d01618 (i am using ankihub)

### Problem description

I encountered an issue while attempting to bind the Up Arrow key to the "Reveal Cloze" function in anking overhaul cloze one by one cards. I tried two different methods to achieve this customization, but both were unsuccessful.

#### Method 1: Using the Anking Note Types Easy Customization Addon

1. Install and enable the Anking Note Types Easy Customization Addon in Anki.
2. Navigate to the "clozes" section of the "general" tab.
4. Attempt to bind the Up Arrow key to the "Reveal Cloze" function.
5. Verify if it now works. (it doesn't)

The addon just replaced 
```
// ##############  CLOZE ONE BY ONE  ##############
var revealNextShortcut = "N"
```
with

```
// ##############  CLOZE ONE BY ONE  ##############
var revealNextShortcut = "Up"
```
That makes it unsurprising why it didn't work.

#### Method 2: Manual Modification of the Back Template Code

I replaced
```
// ##############  CLOZE ONE BY ONE  ##############
var revealNextShortcut = "N"
```
with

```
// ##############  CLOZE ONE BY ONE  ##############
var revealNextShortcut = "Qt.Key_Up"
```

#### Expected Behavior
In both methods, the intention was to bind the Up Arrow key to the "Reveal Cloze" function successfully. Since i am already using other arrow keys for other Anki functions, I believed that using `Qt.Key_Up` should work with your note type.

#### Actual Behavior
After following the described steps in both methods, I found that the Up Arrow key did not trigger the "Reveal Cloze" function. The key binding did not seem to have any effect.

#### Additional Information
Anki version: 2.1.63
Operating System: Windows 10 22H2

#### Checklist

 - [X] I've restarted Anki to see if it helps
 - [X] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [X] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.

**Comment by AnKingMed** [comment]
Try `var revealNextShortcut = 38`

I'm not sure if that would work or not but worth a shot.

Could try a few of these: https://www.toptal.com/developers/keycode

**Comment by aly-k** [comment]
Thanks for the prompt response and providing such a useful site !
`var revealNextShortcut = ArrowUp` worked
