### ISSUE TITLE
Certain image occlusions don't scale properly on AnkiMobile

### ISSUE THREAD

**Issue by rtey31** [AnKing-VIP/AnKing-Note-Types#143]
#### Which Note Type (and version) is this about?

IO-one by one

#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Really appreciate this add-on, but I'm having an issue with image occlusion on mobile. 

I've made a grand total of two image occlusion cards with this add-on, and one of them displays perfectly on the app. The other one doesn't show the occlusions on the correct parts of this image. I edited the card to show the issue clearly: 

#### Correct version: 
![Correct version](https://github.com/AnKing-VIP/anking_notes_addon/assets/7313953/d56b4c0b-b8ef-453f-88da-996c6301d22b)

#### Mobile: 
![Mobile](https://github.com/AnKing-VIP/anking_notes_addon/assets/7313953/a594c724-f49f-4442-9b85-7b720c4048a5)

I think this has something to do with the images scaling and the occlusions not, or the other way around, but I'm not sure. 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [n/a] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.62, AnkiMobile 2.0.95
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*

Windows 10, iOS 16.5.1

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

I would really appreciate some insight into this issue. If it's not a bug, how can I make sure all of my cards appear correctly on mobile?

**Comment by AnKingMed** [comment]
Can you upload a file with your card?  You'll need to zip it to attach it here

**Comment by rtey31** [comment]
> Can you upload a file with your card? You'll need to zip it to attach it here

Here you go: [Deoxyribose IO.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/11997344/Deoxyribose.IO.zip)

**Comment by rtey31** [comment]
Any ideas on what’s causing this issue? I haven’t been able to figure out what causes it and how to avoid it.

**Comment by AnKingMed** [comment]
@RisingOrange I just tested this and I'm encountering the same issue. I even tried making a new note with a fresh IO-one by one install on a new profile and then importing to mobile and it doesn't work. My existing IO one by one note types work. 

I remember we had a similar issue in the past and it had to do with the closet add-on or something. Any idea what's going on here?  

@abdnh feel free to chime in if you have time since @RisingOrange is a bit busier lately

**Comment by AnKingMed** [comment]
My existing IO one by one notes are working fine and making IO one by one notes in existing profiles where it's working is fine

**Comment by RisingOrange** [comment]
@AnKingMed I reproduced the issue when using the image from [Deoxyribose IO.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/11997344/Deoxyribose.IO.zip). It seems to me that the problem only occurrs for svg files. (The image from the zip file is an svg file.) It works fine for jpg and png files. Does this match you observations?

**Comment by AnKingMed** [comment]
[test IO.apkg.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/12074466/test.IO.apkg.zip)

This is a jpg and doesn't work for me on mobile (works on desktop)

**Comment by RisingOrange** [comment]
@AnKingMed That's weird, it works for me on AnkiMobile. I used a new Anki profile, installed the note types add-on and imported the `IO-one by one` note type through it, and imported your note, then synced to mobile.
Are the positions of the occlusions off for you, or are they missing completely on mobile?

**Comment by AnKingMed** [comment]
That's exactly what I did except I didn't sync to mobile, I exported and then sent it to my phone and imported on mobile. Maybe that's why? Perhaps didn't sync the closet .js and .css files? Could that have done it?

They're completely missing for me. 

I'm also on the Anki beta 20096.3 so that could be it? Like I said, it works on my main profile though

**Comment by AnKingMed** [comment]
> Svg files still don't work for me on AnkiMobile, but that's not such a big problem, I guess?

That's probably an ok limitation for now

@rtey31 does this address the issue or explain the issue you were having with your note?
