### ISSUE TITLE
Anking note types names.

### ISSUE THREAD

**Issue by JChatara** [AnKing-VIP/AnKing-Note-Types#144]
#### Problem description
When I download cards off the ankihub they named the notetype "AnKingOverhaul (AnKing / AnKingMed)" but when I go into the "Anking note types" add on and click on the "AnkingOverhaul" tab it states "The notetype is not in the collection." I had to remove the  "(AnKing / AnKingMed)" part from the note name for it to recognize it is indeed in my collection. it would be nice if the name didn't have to be edited to function across add ons.
 

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X ] I've restarted Anki to see if it helps
 - [ X] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
Version ⁨2.1.65 (aa9a734f)⁩

```
2.1.##
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
Windows 11

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
"The notetype is not in the collection."
```

**Comment by AnKingMed** [comment]
Leave the name the same. Just click "import" on the addon and it'll work

**Comment by dochypermoose** [comment]
Hey @AnKingMed is the expectation that we're then supposed to move the notes over to the imported Note Type? I clicked "import" and this is all that I can see having happened:

![Screenshot 2023-09-18 at 7 17 43 PM](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/25800800/bd024876-15a4-4292-a87f-e3e5d68a8248)

**Comment by AnKingMed** [comment]
No that's fine. It'll show that it has 0 but the addon will still modify the AnkiHub version of the note type
