### ISSUE TITLE
autoopen not working on Ankidroid

### ISSUE THREAD

**Issue by shmuelsash** [AnKing-VIP/AnKing-Note-Types#147]
#### Which Note Type (and version) is this about?
Up to date

#### Problem description
Autoreveal works on desktop but not on mobile
I have additional fields set to autoreveal but its not working (this is the 1st time i tried so cant say if it was working before)

<p align="center">
<img src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/35056305/a1a63444-8d31-4e10-b662-0efa45c8f77a" height="500">
</p>

#### Checklist

 - [X] I've restarted Anki to see if it helps
 - [X] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] ~My issue disappears when I hold shift while starting Anki.~
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.

#### What Anki version are you using?

```
Windows: 2.1.65 (aa9a734f)⁩
Android: 2.16.2
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

```
Android 13
```

**Comment by AnKingMed** [comment]
@abdnh I confirmed that this is happening to me too. Doesn't happen on iOS but does on Ankidroid. Any idea why?

**Comment by shmuelsash** [comment]
Whoops 
Seems like i already posted abt this before

Ig i did try it 😂 
https://github.com/AnKing-VIP/AnKing-Note-Types/issues/134#issuecomment-1669374262

**Comment by abdnh** [comment]
I pushed a fix that's working for me on AnkiDroid. Will appreciate testing on AnkiMobile to make sure there are no regressions.
