### ISSUE TITLE
All clozes turn green now

### ISSUE THREAD

**Issue by Wildspin9** [AnKing-VIP/AnKing-Note-Types#150]
Note type: AnkingOverhaul, version 7bd30db. On anki 2.1.64 qt6 m1 macbook air. Ventura 13.5

Appreciate the new feature, but after doing a cloze one-by-one (where the cloze changes to green) - afterwards all my other clozes stay green as well. If I go back out to the main screen then go back to doing my reviews they change back to blue, until i run into another cloze one-by-one, then they all turn green again. 

This also happens on mobile as well.

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.

**Comment by AnKingMed** [comment]
I ran into this as well. I've asked @abdnh to look into it

**Comment by talkael** [comment]
Still having this issue @abdnh

**Comment by abdnh** [comment]
@talkael the update was not released yet. Please wait.
