### ISSUE TITLE
One-by-one Cloze cards change text color on subsequent Cloze cards

### ISSUE THREAD

**Issue by trmchugh** [AnKing-VIP/AnKing-Note-Types#151]
#### Which Note Type (and version) is this about?

AnKingOverhaul (AnKing / AnKingMed)

#### Problem description

Since the last update to this add-on on 2023-08-29, my one-by-one cloze cards have had green cloze fields on the front of the card. This seems to be expected behavior. However, after reviewing a single one-by-one cloze card in my deck, all subsequent cloze cards (including single cloze cards) show cloze fields in a green font. This continues indefinitely until I exit the review session.

When this issue arises, if I return to the Decks screen of Anki and then reopen my deck to resume reviews, the cloze fields return to normal, and appear blue on the front of my cards. I can review normally until I reach another one-by-one cloze card, and then clozes for that card and all subsequent cards will appear green, regardless of whether it is a one-by-one card or not.

I can also simulate this issue in the card browser in Anki. If I browse for a tag that includes a one-by-one cloze and then use the Preview feature, I can use the right arrow to move through and preview several cards within the card browser itself. The cards appear normally until I reach another one-by-one cloze card, and then the same change to the color of the cloze field is seen. I've attached some screenshots of this sequence below.

<img width="1728" alt="Screen Shot 2023-08-31 at 6 53 10 PM" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/85208512/5029ba53-1db0-436e-8fb4-f061bf817a62">
^ Here, I am previewing cards in the Browser. Cloze fields appear blue, as expected.
<br/><br/>

<img width="1728" alt="Screen Shot 2023-08-31 at 6 53 19 PM" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/85208512/b18bf649-126e-438e-9da1-c908221cb6bc">
^ One-by-one cloze card with green text. Seems to be expected behavior.
<br/><br/>

<img width="832" alt="Screen Shot 2023-08-31 at 6 53 42 PM" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/85208512/f7b2d65c-f9ee-44a1-bf85-0e38fd3bc45b">
^ Subsequent single cloze cards appear green.
<br/><br/>

<img width="1728" alt="Screen Shot 2023-08-31 at 6 53 31 PM" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/85208512/5afecedc-2e97-4ff5-96fc-6a7ff70a6cac">
^ The back sides of subsequent cloze cards also appear green.
<br/><br/>

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.65
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*
macOS Monterey Version 12.5.1

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
reported and addressed [here](https://github.com/AnKing-VIP/AnKing-Note-Types/issues/150). Going to release an update tonight
