### ISSUE TITLE
 "Text-to-Speech in Anki Overhaul Notetype Automatically Reads out  Answers on Card Back"

### ISSUE THREAD

**Issue by fredjoe7** [AnKing-VIP/AnKing-Note-Types#152]
#### Which Note Type (and version) is this about?
Anking overhaul version 6c9041e
#### Problem description

 When using the "onebyone" feature in the Anki Overhaul notetype with text-to-speech enabled, the card's back side automatically reads out the answer even though the answers are hidden and yet to be revealed one by one during review.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.66
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Windows 11

**Comment by AnKingMed** [comment]
This has already been reported [here](https://github.com/AnKing-VIP/AnKing-Note-Types/issues/105) but unfortunately isn't something we can easily fix. I'm closing this issue and leaving the other open so we can still track it
