### ISSUE TITLE
V3 Scheduler is messing up my daily limit

### ISSUE THREAD

**Issue by apinchok25** [AnKing-VIP/AnKing-Note-Types#156]
#### Problem description

I just started using the V3 scheduler and since then it has been messing up my algorithm, especially my new cards in a deck. My daily limit is 9999 and new cards per day is 9999 but I don't see all of my cards in one day and I feel like I never do. It says I have reached my daily limit but I don't understand how that is possible.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

Version ⁨2.1.65 (aa9a734f)⁩
```
2.1.##
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

MacOS

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
I don't think this is related to this addon or the note types.  This would best be asked about in forums.ankiweb.net
