### ISSUE TITLE
Preserve user settings when updating note type

### ISSUE THREAD

**Issue by Leg58D** [AnKing-VIP/AnKing-Note-Types#159]
#### Which Note Type (and version) is this about?
Anking Overhaul 1727733
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [X] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [X] I've checked if anyone else suggested this feature before by looking through the issue reports.

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
23.10 (51a10f09)⁩
```

#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*
MacOS, Ventura 13.6.1
#### Problem case

*Is your feature request related to a problem? If so, please describe it here.  E.g.: "My workflow is such and such, and this and that would help."* 

Every time AnkiHub updates the note type and pushes it out to users, it resets all the personalized settings.  I have to go through and set font, text color, hint auto-reveal (for lecture notes).  This wouldn't be an issue if it was an infrequent occurrence, but since we get an update to the note type what seems like once a week, it gets annoying. 

#### Solution

*Concisely describe the solution you would like*
Preserve user defined settings for note types as specified in the AnKing Note Types window when pushing updates from AnkiHub.  To make this actually work, you would also have to add an "auto-reveal hints" option within the AnKing Note Types window. This would make the most sense if we could simply click checkboxes for which hints we wanted auto-revealed and leave all others set to auto-collapsed.

*Concisely describe alternatives you've considered (if any)*
Not updating note type
Manually fixing the problem every time I update.

#### More information

*Additional context: Add any other context or screenshots about the feature request here.*

**Comment by Leg58D** [comment]
I'm manually editing the styling for the hint reveal because I don't see any boxes for selecting auto reveal.  Either way though, any changes I make in the AnKing Note Type window gets reset every time the note type updates.

**Comment by Leg58D** [comment]
Where would I find the auto reveal hint toggle?

**Comment by abdnh** [comment]
> Where would I find the auto reveal hint toggle?

It's under the Hint Buttons section. Note that the toggles will only be shown for applicable note types such as AnKingOverhaul.
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/41397710/b883b76a-1e09-44d3-85eb-c8a252b50423)

Can you share a sample card so I can check what's happening?

**Comment by AnKingMed** [comment]
Make sure you're on the right tab. Then scroll down a bit

![CleanShot 2023-12-04 at 18 54 20](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/57678116/73bc891d-aea8-4bb6-a8d2-462dac92fac0)

Also, i just changed my settings via the note types add-on and then updated my notes and the changes stayed and were not reset. I wasn't able to replicate what you're experiencing.

**Comment by abdnh** [comment]
> How do you want me to share a sample card?

You can zip the apkg and upload it here

**Comment by Leg58D** [comment]
<img width="1317" alt="image" src="https://github.com/AnKing-VIP/AnKing-Note-Types/assets/62848584/dd4ea1d8-0678-46e2-bb65-e30c523f89a0">
This may be part of my problem.  Not sure why "General" is the only Note Type section that has anything under it.
[For Anki GIt.apkg.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/13620727/For.Anki.GIt.apkg.zip)

**Comment by Leg58D** [comment]
So apparently I had to press import at the bottom of the window and it brought all the options in.  I'm sure that was in the instructions somewhere I thought I didn't need to read...

**Comment by AnKingMed** [comment]
Forgot to include that. Is it working now?
@abdnh is it possible that it's because it wasn't "imported" that its not preserving settings?

**Comment by abdnh** [comment]
The add-on doesn't recognize the AnKingOverhaul note type from AnkiHub because it expects it to be named exactly "AnKingOverhaul", so it seems it's not compatible with AnkiHub.
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/41397710/d46dfe16-9873-40ef-b184-957ff2410484)


@AnKingMed what do you think? Should we make the add-on recognize "AnKingOverhaul (AnKing / AnKingMed)" and similar names? Looks like the AnkiHub add-on preserves changes to note types so this should work and no settings should be reset. @RisingOrange probably has a better idea.

**Comment by AnKingMed** [comment]
Would be good to get @RisingOrange 's thoughts

**Comment by RisingOrange** [comment]
@abdnh The add-on has some code to make it compatible with the AnkiHub version of the AnKing note types. 
Though I'm not sure what goes wrong in this case.

**Comment by RisingOrange** [comment]
@AnKingMed @abdnh The add-on has some code to make it compatible with the AnkiHub versions of the AnKing note types. Though I'm not sure what goes wrong in this case.
I'll look into it.

**Comment by RisingOrange** [comment]
@Leg58D There is a new version of the AnKing note types add-on! With this new version your settings for the note types will be preserved across updates. Note that manual changes to the note type won't be preserved, only the ones you make via the AnKing Note Types dialog.

**Comment by RisingOrange** [comment]
@AnKingMed @abdnh 
Previously changes were only preserved if you had the "base" version of the note type in your collection. For example if you had the **AnKing Overhaul** note type, changes to the **AnKing Overhaul (AnKing / AnKingMed)** note type would be preserved across note type updates. However that didn't work if you didn't have **AnKing Overhaul** in your collection.
This is now fixed.

**Comment by AnKingMed** [comment]
awesome! Thank you!
