### ISSUE TITLE
IO one by one toggles not working anymore (Re: Issue 158)

### ISSUE THREAD

**Issue by Stillmatic27** [AnKing-VIP/AnKing-Note-Types#160]
>https://github.com/AnKing-VIP/AnKing-Note-Types/issues/158#issue-2020650856

After this issue was solved, another popped up, the note type now colliding with "edit field during review cloze" addon

(OS: Windows 10 and Linux Ubuntu: both on anki version 21.10.1)

[385888438.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/13567496/385888438.zip)

[Selected Notes.apkg.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/13567497/Selected.Notes.apkg.zip)

The addon number, file and the specific note is attached.

@AnKingMed @abdnh

**Comment by AnKingMed** [comment]
@abdnh youre probably tired of these bugs 😂 but can you look into this one when you get a chance?

**Comment by Stillmatic27** [comment]
@abdnh just got a new update for the AnKing note types addon and the note seems to work now! Thank-you so much ❤️
