### ISSUE TITLE
Image Occlusions Moving After Adding Card

### ISSUE THREAD

**Issue by MattAwesome246** [AnKing-VIP/AnKing-Note-Types#161]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*: This is my first time reporting a bug, so I want to apologize in advance if I filled this report incorrectly. I recently downloaded the IO-one by one add-on to help with memorizing biochemical pathways for the MCAT. However, every time I add an image occlusion, it moves and fails to cover what I want on the image. Only when I deselect and select the "Back Side Only" option does it cover what was intended. I've included pictures of what I see when I first open the card and after I toggle the "Back Side Only" option.

First opening the card - incorrect: 
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139718377/a31f390f-4eab-4df9-b962-714be4c2daf8)

After toggling "Back Side Only" option - how it should look:
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139718377/774c4e70-9cea-48d2-9bec-30264d2083ff)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?: Version 23.10.1 Qt 6

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
23.10.1
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Windows 11 Pro

#### Error message (if any): N/A

*If you've received an error message, please copy and paste it between the backticks below:*

I'd appreciate any help or advice. Thank you in advance!

```

```

**Comment by AnKingMed** [comment]
Is this just for the previewer? I'm assuming that's what you mean by the "back side only" button?

**Comment by MattAwesome246** [comment]
Hi! Sorry for the late response. 

This is for both the previewer and when working on the card. When I get to this card, the occlusions are off, and I have to toggle the "back side only button" to place the occlusions in the correct spot.

I know it's the holidays, so wishing you a Merry Christmas! Thank you for all you do :)

**Comment by AnKingMed** [comment]
Does this occur without any add-ons? (hold shift when starting)

Can you export some of the notes that aren't working and share here? (you'll need to zip them)

Merry Christmas to you too!

**Comment by MattAwesome246** [comment]
Unfortunately, it still occurs without any add-ons. 

Yes, I will export some of the notes that aren't working and share them (see attached).

Thanks again!

[Problem Cards with IO one by one.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/13773164/Problem.Cards.with.IO.one.by.one.zip)

**Comment by AnKingMed** [comment]
I don't know why this worked but here's what I did to fix it
1. using the anking note types add-on, installed the Physeo one-by-one note type
2. converted all IO one by one notes to the Physeo one by one note type
3. deleted the IO one by one note type
4. using the AnKing Note Types add-on, imported the IO one by one note type
5. re-converted them back

You could try that? We could look deeper into it but nobody else has reported it and it seems to be working ok when I do this

**Comment by MattAwesome246** [comment]
Thanks for looking into this for me. I will give this a go and let you know what happens.

**Comment by MattAwesome246** [comment]
Hello AnKing Med, my apologies for responding so late. When you're studying for the MCAT, you sometimes forget how much time has flown by lol. 

Anyways, I did what you said and it works! Looks like there was an issue with the IO one by one note type. Simply deleting it and importing it using the Anking note types add-on did the trick. Thank you so much for your help!
