### ISSUE TITLE
my setting doesn't get saved

### ISSUE THREAD

**Issue by Debar131** [AnKing-VIP/AnKing-Note-Types#162]
#### Which Note Type (and version) is this about?
anking addon---->general or (mostly the anking overhaul cards)
#### Problem description
when i try to study using ankihub cards there are tags on the screen which is really annoying so when i try to turn off that feature in anking addon by disabling the tag container the setting doesn't get saved so when i open the anking addon after that the tag container is still on
*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ yes] I've restarted Anki to see if it helps
 - [ yes] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ yes] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [yes ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
 anki 23.12 (beta) version
*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
windows
*Please include OS version as well if possible*
windows 11

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Can you try going to the ankingoverhaul tab and then importing the note type if needed and then adjusting the setting from that tab instead of the general tab?

**Comment by Debar131** [comment]
I'm sorry for the late reply, yes it works by going on the anking overhaul tab, I think I found the cause of the problem, there was one note type that I hadn't imported yet, I imported that card type then went and turned on the tag container for all card types and saved it after that i went to turn off the tag container for all card types starting from last then finally i did it for the general and it works, if anyone having this problem i hope this solution work for them too, anyway thank you so much for your help i appreciate it and I'm sorry i wasted your time.

**Comment by AnKingMed** [comment]
Great, glad you figured that out! We can try to improve things moving forward
