### ISSUE TITLE
One by One Cloze deletions not revealing answer after hitting spacebar unless I double click

### ISSUE THREAD

**Issue by ajayp1** [AnKing-VIP/AnKing-Note-Types#163]
#### Problem description

After updating to V12 from V11, I am having to double click the screen after pressing space bar for the answer of a cloze deletion to be revealed. If I don't double click, the options for "Again" "Hard" "Good" appear at the bottom of the screen but the deletion itself doesn't go away.

Downloaded the AnKing NoteType addon, restarted, updated all note types, the issue persists....

edit: issue appears to be less frequent (not as many cloze cards affected) when restarting Anki while holding shift, but is still present to some extent. I may just not be observing properly, as it is occurs randomly even when NOT holding shift upon starting Anki

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
23.10.1
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*
Windows 11

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
can you export one of the notes you're having issues with and upload here? You'll have to zip it in order to attach

**Comment by ajayp1** [comment]
Sure, here is one of the notes.
[anking_v12_onebyone_BUG_NOTE.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/13760214/anking_v12_onebyone_BUG_NOTE.zip)

**Comment by AnKingMed** [comment]
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/57678116/2d0f22ff-f4ae-414e-9dba-508e4d1f43d1)
I'm getting this for some reason (not sure why as I'm on 23.10.1). Can you try exporting some other way? Not sure why that's happening

**Comment by ajayp1** [comment]
Hmmm that is weird. How about if I just give the code for the note type? This is a different note which gave the same issue.

Front template:
https://pastebin.com/S0B512kr

Back template:
https://pastebin.com/pQ95XfWH

**Comment by AnKingMed** [comment]
Probably would be best to get the actual note if possible. How did you export it?

**Comment by ajayp1** [comment]
I did Ctrl+Shift+E in the browser. I tried it again but checked the "Support older Anki versions" this time:
[anking_v12_onebyone_BUG_NOTE.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/13760526/anking_v12_onebyone_BUG_NOTE.zip)

**Comment by ajayp1** [comment]
I just realized that when I click the ' key it reveals the cloze answer (along w all other 3rd party buttons). Perhaps it's related to that?

**Comment by AnKingMed** [comment]
I just tested that and everything is working fine for me. I must not understand what your issue is. Can you draw it out with screenshots and/or video?

**Comment by ajayp1** [comment]
Yeah it happens even when I start Anki while holding Shift. However much less frequent.

Ah apologies, when I clicked "edit" then "Cards..." the top "Card Type" drop out was set to "AnKing One by One:OME One by One...." or something like that. However now when I look at the Note Type listed in the card info (Ctrl+Shift+I in browse menu) it states that it's the AnKingOverhaul (AnKing / AnKingMed) card.

I am assuming the note type underwent changes in the v12 update (?), and it would also explain why this happens when addons are disabled. Given that the answer is revealed when I hit the "toggle all" shortcut, I assume there's some bug related to the cloze reveal? entirely guessing

**Comment by AnKingMed** [comment]
Yeah the one by one feature is built in to the AnKingOverhaul note type. 

@abdnh or @RisingOrange do you have any idea at all why this would be happening? I can't replicate it and I've not had any other reports of this happening

**Comment by ajayp1** [comment]
I'm noticing that Anki is slower in general after updating to 23.10 and adding AnkiHub. Not entirely sure why, was running smoothly before.

I did replace my m.2 SDD just before updating but I doubt that is relevant.

thanks for your availability on christmas eve!

**Comment by abdnh** [comment]
> Here is an example. If you look at the bottom, you can see I pressed spacebar but the answer isn't revealed.

@ajayp1 This is probably a known graphics issue affecting 23.10+. Please try switching the video driver from the preferences.

> I'm getting this for some reason (not sure why as I'm on 23.10.1).

@AnKingMed This is caused by the Special Fields add-on.

**Comment by RisingOrange** [comment]
> I'm noticing that Anki is slower in general after updating to 23.10 and adding AnkiHub.

Which actions did you notice being slower? It's true that the startup of Anki is slower with the AnkiHub add-on - we should fix that as it's a bit annoying. Syncing takes longer because the AnkiHub add-on has to download updates from AnkiHub. Other actions should not be slower.

**Comment by ajayp1** [comment]
> > I'm noticing that Anki is slower in general after updating to 23.10 and adding AnkiHub.
> 
> Which actions did you notice being slower? It's true that the startup of Anki is slower with the AnkiHub add-on - we should fix that as it's a bit annoying. Syncing takes longer because the AnkiHub add-on has to download updates from AnkiHub. Other actions should not be slower.

Things like moving through the browse cards menu, hopping out of a deck take longer. Though I wouldn't be surprised if this is due to a graphics issue as @abdnh mentioned!

**Comment by ajayp1** [comment]
> > Here is an example. If you look at the bottom, you can see I pressed spacebar but the answer isn't revealed.
> 
> @ajayp1 This is probably a known graphics issue affecting 23.10+. Please try switching the video driver from the preferences.
> 
> > I'm getting this for some reason (not sure why as I'm on 23.10.1).
> 
> @AnKingMed This is caused by the Special Fields add-on.

I actually did install the Special Fields add-on as I was transitioning to v12 so that makes sense. Will attempt switching the video driver

**Comment by AnKingMed** [comment]
@abdnh does 23.12 fix the graphics issue?

**Comment by abdnh** [comment]
> @abdnh does 23.12 fix the graphics issue?

No. The issue appeared after a Qt update.

**Comment by ajayp1** [comment]
I changed the video driver to OpenGL and things are running smoothly (so far)! I'll post another issue if anything comes up again. thanks all
