### ISSUE TITLE
Unable to add a new card 

### ISSUE THREAD

**Issue by edminster101** [AnKing-VIP/AnKing-Note-Types#164]
#### Which Note Type (and version) is this about?
ALL  types 
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

Hi , I am currently on the the following Anki version Version ⁨23.10.1 (fac9e0ee)⁩
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3. I am unable to add any new cards regardless of the note type. I use a MacBook Pro M1 and I am updated to the latest software on my Mac ( Mac Sonoma 14.2 ) I have updated all my add ons and removed any that were giving me issues.
#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [x ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ x] I've tried to disable add-ons to see if there are any interactions present
 - [ x] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
23.10.1 (fac9e0ee)⁩
Python 3.9.15 Qt 6.5.3 PyQt 6.5.3
*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*
Mac Sonoma 14.2 
#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Can you describe this a bit more? You're not able to add a new card that has the AnKing note types from the addon? Or you're not able to import the note types from the addon? 
Screenshots would be helpful

**Comment by edminster101** [comment]
I am unable to add a new card that has the Anking note types from the addon. I am currently able to add new cards on my iPad and iPhone; however, on my Mac M1, when I simply click on  add within the deck I am currently studying, it just does not respond. It's almost like the add feature within the deck is disabled on my Mac.

**Comment by edminster101** [comment]
I have also added screenshots of my add-ons etc 
![Anki 1](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/155158406/59472f3b-077d-4707-b68e-886bac576312)
![Anki 2](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/155158406/74461f16-080f-4495-8d95-695a289edd9b)
 I hope this will be enough to determine why I am unable to add new cards within the deck on my Mac M1. Thank you in advance for your help . Just FYI as I had mentioned previously , I am able to add cards with my iPhone and Ipad but not on my desktop which is how I prefer to study on for various reasons.

**Comment by AnKingMed** [comment]
> I am unable to add a new card that has the Anking note types from the addon.

I don't understand what this means. Can you walk me through exactly what actions you are doing and where you get an error?
