### ISSUE TITLE
'Align text to the left' doesn't work on or supported by 'Anking' Note type When Using 'List', Please Help⚠️

### ISSUE THREAD

**Issue by CaptainDead** [AnKing-VIP/AnKing-Note-Types#167]
#### Which Note Type (and version) is this about?
Anking Note Type,  I am sorry but I don't know how to check version of addon
#### Problem description

**'Align text to the left' is not working on Anking note type as it is supposed to work, when 'List' is enabled .** 
Normally When using a 'List' either Numbered or Unordered, Text automatically gets aligned to left👍

Now, to help you understand the problem better, I will show you how it looks on a normal Cloze Note type and then on Anking Note Type.

In Normal Cloze Type, 'Align text to the LEFT' when **not using** 'List" - 
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139457914/df808cc0-5041-44e1-84be-e130c19b0026)

In Normal Cloze Type, 'Align text to the left' when **using** 'List" - 
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139457914/fbf3c986-ec4f-4a0a-8481-5bac233a47d4)

See how its the same in both, aligned to left as it should be, now let's take a look at the Anking Note type.

In Anking Note Type, 'Align text to the left' when **not using** 'List" - 
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139457914/10b5e92b-05e1-45c5-9433-411c1a73230e)

Now, In Anking Note Type, 'Align text to the left' when **using** 'List" - 
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139457914/c9fac770-5c78-4ad2-9b24-782d5bdf807b)

I hope the issue is visible now, The text is not aligned to the left when we use List.

I love your note types and was thinking about changing all my note types in to Anking and Basic-Anking but sadly because of this I can't change all of them into Anking as I use 'List' option in quite a few Cards.
I hope the issue is clear, I request that you guys fix this if you can, I would be very grateful,
Thanks.

#### Checklist

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

```
Anki Version ⁨23.12.1 (1a1d4d54)⁩
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Edition	Windows 11 Pro
Version	22H2
Installed on	‎8/‎21/‎2023
OS build	22621.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
I tried playing around with the styling and unfortunately wasn't able to figure out what's causing it to do that sorry!

**Comment by CaptainDead** [comment]
> I tried playing around with the styling and unfortunately wasn't able to figure out what's causing it to do that sorry!

So it can't be fixed? aah sad, its okay, thanks👍

**Comment by AnKingMed** [comment]
It probably could be but I spent about 15 minutes on it and couldn't figure it out so its not a simple fix.. it may involve restructuring a lot of the styling unfortunately
