### ISSUE TITLE
IO one-by-one not compatible with clickable tags v20

### ISSUE THREAD

**Issue by hsyuen02** [AnKing-VIP/AnKing-Note-Types#175]
Which Note Type (and version) is this about? - IO - one by one

#### Problem description
Occlusions not showing up when "clickable tags v20" is enabled

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
23.12.1
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

MacOS

**Comment by AnKingMed** [comment]
1. Can you delete and redownload the clickable tags add-on?
2. Can you update your note types with the AnKing Note Types add-on, then go to the IO-one by one tab and click "reset" in the bottom left?

**Comment by hsyuen02** [comment]
The issue is resolved now, thank you
