### ISSUE TITLE
Change 👑 to ❓ in the Sketchy-Cloze note type for one-by-one

### ISSUE THREAD

**Issue by AnKingMed** [AnKing-VIP/AnKing-Note-Types#176]
@abdnh can you change the default symbol for one by one feature on the Sketchy-Cloze note type? I couldn't figure out how to do that since it's a script that's shared with everything. Maybe we just need to manually put the code in and leave a reminder for ourselves about that?

**Comment by abdnh** [comment]
I added a way to override the default symbol for any notetype.
