### ISSUE TITLE
IO one by one zoom

### ISSUE THREAD

**Issue by dianacd28** [AnKing-VIP/AnKing-Note-Types#178]
#### Which Note Type (and version) is this about?

IO one by one

#### Problem description

I recently updated anki and now the cards I made using the "IO one by one" note type aren't working like they used to before. 
They used to show up with more zoom, but they don't anymore. I've already tried to create new cards using the same note type to see if it fixes the problem, but it doesn't work. The cards look tiny and I can't read them. I'll attach some images so you can see the comparison (the first one is the way they look after I updated anki and the second one is the way the used to look).

I kindly ask for your help since I have a big test coming up and those cards are really important.

![anki](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/166483257/e01e0c4b-be02-49ac-b820-996fa4bdb1ff)
![anki 2](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/166483257/f09d6117-538e-451a-a5bb-919e9b1c9cda)

PS: English isn't my first lenguage, so I apologize for any mistakes, I tried to explain the issue the best I could.

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.24.04
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Windows 11

*Please include OS version as well if possible*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
Try changing these settings in the "styling" tab of the note type and see if it fixes it. You could just remove this paragraph or change the 95vw and 80vh to 100% or something like that

```
/*~~~~~~~MAX IMAGE HEIGHT/WIDTH~~~~~~~*/
img {
  max-width: 95vw;
  /* note: changing this may impact the occlusions */
  max-height: 80vh;
}
```

**Comment by CaptainDead** [comment]
> Try changing these settings in the "styling" tab of the note type and see if it fixes it. You could just remove this paragraph or change the 95vw and 80vh to 100% or something like that
> 
> ```
> /*~~~~~~~MAX IMAGE HEIGHT/WIDTH~~~~~~~*/
> img {
>   max-width: 95vw;
>   /* note: changing this may impact the occlusions */
>   max-height: 80vh;
> }
> ```

PLEASE integrate this change officially into the addon, I spent so much time trying to understand why I am having this issue (the same issue as the above) It gave me a crazy headache as I was worried I would have to redo all of my stuff or that I will not be able to study from my cards anymore, my exam is very near, I was nearly fuked but luckily I realized its because of the new update, I had a copy of the old addon so I copy pasted that and clicked reset on the banking note types I used and everything was back to normal.

I even wrote the whole explanation of this on my note pad only to realize someone already made a issue about this😭
and
PLEASE so many people are probably having this problem and might be unaware as to why it is happening, give another update and fix this, a big exam of India (NEET) is in 25 days and I think many people use anki, so I request to fix this, thanks.

Before Update - 
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139457914/c75750cd-9f08-4b85-91f5-7e6497f57fa9)

After Update - 
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139457914/ad94e2e4-167c-4d4a-8c35-5ba46b9852ae)

**Comment by CaptainDead** [comment]
> #### Which Note Type (and version) is this about?
> IO one by one
> 
> #### Problem description
> I recently updated anki and now the cards I made using the "IO one by one" note type aren't working like they used to before. They used to show up with more zoom, but they don't anymore. I've already tried to create new cards using the same note type to see if it fixes the problem, but it doesn't work. The cards look tiny and I can't read them. I'll attach some images so you can see the comparison (the first one is the way they look after I updated anki and the second one is the way the used to look).
> 
> I kindly ask for your help since I have a big test coming up and those cards are really important.
> 
> ![anki](https://private-user-images.githubusercontent.com/166483257/320753569-e01e0c4b-be02-49ac-b820-996fa4bdb1ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI0NjEsIm5iZiI6MTcxMjY5MjE2MSwicGF0aCI6Ii8xNjY0ODMyNTcvMzIwNzUzNTY5LWUwMWUwYzRiLWJlMDItNDlhYy1iODIwLTk5NmZhNGJkYjFmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxOTQ5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMGMzOTJmYWQ0ZWZjMjFmYWRjMTlkMTZiOTYwODE3YzcwYjM4ZjRlZGI3YTMzNWI4NzE1MTg2ODk2ODEwMGYxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2k7dEDbhKPSmSpQfQOQKUjFMIK74uy4klng1SVaAi8w) ![anki 2](https://private-user-images.githubusercontent.com/166483257/320753638-f09d6117-538e-451a-a5bb-919e9b1c9cda.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTI0NjEsIm5iZiI6MTcxMjY5MjE2MSwicGF0aCI6Ii8xNjY0ODMyNTcvMzIwNzUzNjM4LWYwOWQ2MTE3LTUzOGUtNDUxYS1hNWJiLTkxOWU5YjFjOWNkYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxOTQ5MjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZWZiNjI4YjQ5ZTNiMzc1MzMyODM2ODkyZWE4NDg3ODIyMTdmZmM0MDI1MDVhZGExNGYwNDZkNjViYzYyZDhkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.HEwHHsTq8G6khTaAZbwtzHpwTQG4gpm1ziVphyqVMVU)
> 
> PS: English isn't my first lenguage, so I apologize for any mistakes, I tried to explain the issue the best I could.
> 
> _Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?_
> 
> #### Checklist
> _Please replace the space inside the brackets with an **x** if the following items apply:_
> 
> * [x]  I've restarted Anki to see if it helps
> * [x]  I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
> * [ ]  I've tried to disable add-ons to see if there are any interactions present
> * [ ]  My issue disappears when I hold shift while starting Anki.
> * [x]  I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
> 
> #### What Anki version are you using?
> *Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below
> 
> ```
> 2.1.24.04
> ```
> 
> #### What Operating system are you using? (i.e. MacOS, Windows, Linux)
> Windows 11
> 
> _Please include OS version as well if possible_
> 
> #### Error message (if any)
> _If you've received an error message, please copy and paste it between the backticks below:_
> 
> ```
> 
> ```

Hey bro if the above fix did not work please unzip the file I shared and paste this folder (in addons21 folder) and click replace if asked - 
[952691989.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/14923251/952691989.zip)
addons 21 location - In Anki, click on tools > addons and then choose any addon and click on 'View Files'
and then you can locate the addons21 folder (see the pic)
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139457914/f56681ef-28e0-42a8-a174-fbef106984d6)

Click there and paste the folder u got after unzipping the file I share, click replace if asked, and then go to the anking note types from the Anking option at the top bar and do not click on update if asked,

go to the note types you use and click on 'reset' and then save and maybe also restart and you everything will be back to how it was
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139457914/7e8e5110-13ae-4316-91f6-9c25e840f69e)

**Comment by dianacd28** [comment]
> Try changing these settings in the "styling" tab of the note type and see if it fixes it. You could just remove this paragraph or change the 95vw and 80vh to 100% or something like that
> 
> ```
> /*~~~~~~~MAX IMAGE HEIGHT/WIDTH~~~~~~~*/
> img {
>   max-width: 95vw;
>   /* note: changing this may impact the occlusions */
>   max-height: 80vh;
> }
> ```

Hi. I've tried this and it didn't work, the images got a little bit of zoom, but not enough to be able to read them.

**Comment by dianacd28** [comment]
> ⭐To the guy who shared this issue -
> 
> Hey bro if the above fix did not work please unzip the file I shared and paste this folder (in addons21 folder) and click replace if asked - [952691989.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/14923251/952691989.zip) addons 21 location - In Anki, click on tools > addons and then choose any addon and click on 'View Files' and then you can locate the addons21 folder (see the pic) ![image](https://private-user-images.githubusercontent.com/139457914/320984770-f56681ef-28e0-42a8-a174-fbef106984d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTYyOTMsIm5iZiI6MTcxMjY5NTk5MywicGF0aCI6Ii8xMzk0NTc5MTQvMzIwOTg0NzcwLWY1NjY4MWVmLTI4ZTAtNDJhOC1hMTc0LWZiZWYxMDY5ODRkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQyMDUzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjEzMzRhMTc1ZDkzMzU1ODVlMWRhYzQzNjE4NTQ0Mjc5ZDEzZjVhNzdmMmUxOGU3OGE5YjUyM2UxOTk2NWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NLMhydfCQIl0SqTUzqd16uhfLCJPhV7LB2nH8EmzV10)
> 
> Click there and paste the folder u got after unzipping the file I share, click replace if asked, and then go to the anking note types from the Anking option at the top bar and do not click on update if asked,
> 
> go to the note types you use and click on 'reset' and then save and maybe also restart and you everything will be back to how it was ![image](https://private-user-images.githubusercontent.com/139457914/320985475-7e8e5110-13ae-4316-91f6-9c25e840f69e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTYyOTMsIm5iZiI6MTcxMjY5NTk5MywicGF0aCI6Ii8xMzk0NTc5MTQvMzIwOTg1NDc1LTdlOGU1MTEwLTEzYWUtNDMxNi05MWY2LTljMjVlODQwZjY5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQyMDUzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjJmNGI3MGUxYWQ1MzljMjk2YjdkMmI4ZDhlMWU2MDlkZTg5NzAyZGQyYzRjYTdlYTY4YTM2MjhmYjA5ZWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LekVrUGhhVyyLZGsqcsq30PhvQotMHCbeRSmZc2dmok)

I followed all the steps and it worked perfectly. My cards are back to the way they used to be and I can finally read them! Thank you so much for your reply, it was really helpful.

**Comment by CaptainDead** [comment]
> > ⭐To the guy who shared this issue -
> > Hey bro if the above fix did not work please unzip the file I shared and paste this folder (in addons21 folder) and click replace if asked - [952691989.zip](https://github.com/AnKing-VIP/AnKing-Note-Types/files/14923251/952691989.zip) addons 21 location - In Anki, click on tools > addons and then choose any addon and click on 'View Files' and then you can locate the addons21 folder (see the pic) ![image](https://private-user-images.githubusercontent.com/139457914/320984770-f56681ef-28e0-42a8-a174-fbef106984d6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTYyOTMsIm5iZiI6MTcxMjY5NTk5MywicGF0aCI6Ii8xMzk0NTc5MTQvMzIwOTg0NzcwLWY1NjY4MWVmLTI4ZTAtNDJhOC1hMTc0LWZiZWYxMDY5ODRkNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQyMDUzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZjEzMzRhMTc1ZDkzMzU1ODVlMWRhYzQzNjE4NTQ0Mjc5ZDEzZjVhNzdmMmUxOGU3OGE5YjUyM2UxOTk2NWViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.NLMhydfCQIl0SqTUzqd16uhfLCJPhV7LB2nH8EmzV10)
> > Click there and paste the folder u got after unzipping the file I share, click replace if asked, and then go to the anking note types from the Anking option at the top bar and do not click on update if asked,
> > go to the note types you use and click on 'reset' and then save and maybe also restart and you everything will be back to how it was ![image](https://private-user-images.githubusercontent.com/139457914/320985475-7e8e5110-13ae-4316-91f6-9c25e840f69e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2OTYyOTMsIm5iZiI6MTcxMjY5NTk5MywicGF0aCI6Ii8xMzk0NTc5MTQvMzIwOTg1NDc1LTdlOGU1MTEwLTEzYWUtNDMxNi05MWY2LTljMjVlODQwZjY5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQyMDUzMTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYjJmNGI3MGUxYWQ1MzljMjk2YjdkMmI4ZDhlMWU2MDlkZTg5NzAyZGQyYzRjYTdlYTY4YTM2MjhmYjA5ZWRhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LekVrUGhhVyyLZGsqcsq30PhvQotMHCbeRSmZc2dmok)
> 
> I followed all the steps and it worked perfectly. My cards are back to the way they used to be and I can finally read them! Thank you so much for your reply, it was really helpful.

while I was typing all that I was wondering if I am just wasting my time so I am glad it was helpful, study hard👍🥂

**Comment by AnKingMed** [comment]
@abdnh I think I implemented this to make things not as huge on mobile but it looks like it's causing other issues. Can you revert the change I made to whatever it was before?

**Comment by CaptainDead** [comment]
I dont use Anki app a lot but If I remember it right, the texts are real big in mobile, but images are only big if WE add big images, so its fine.

**Comment by QuietBasil** [comment]
I opened a new issue about the same by opening the "Contact Author" link on the ankiweb webpage of the Anking note types. I did not know there was another github project address too where the same issue was also started.

Here is the link to my issue: https://github.com/AnKing-VIP/anking_notes_addon/issues/28

**Comment by abdnh** [comment]
I reverted the change.

**Comment by AnKingMed** [comment]
Thanks @abdnh. You can go ahead and push a new version of the addon now. If there are a few other bugs worth addressing first you can wait till those are addressed and combine all into one update.

Thank you!

**Comment by CaptainDead** [comment]
Hey there's a small suggestion - it would be nice if there was a option to turn off the low opacity BG color that automatically comes with the Anking Notetypes. 
Like it once caused me a problem - https://github.com/AnKing-VIP/AnkiRecolor/issues/36#issue-2177620015

and ig it would be convenient if there was a turn off setting for that, I always remove it from the styling as it interferes with the theme I choose using 'Recolor' addon and even without that theme problem there are probably other people too whodoesn't want a background. thanks.

This is the styling BG I am talking about - https://github.com/AnKing-VIP/AnkiRecolor/issues/36#issuecomment-1988325209
