### ISSUE TITLE
IO one-by-one specific buttons not loading?

### ISSUE THREAD

**Issue by iuco2** [AnKing-VIP/AnKing-Note-Types#179]
#### Which Note Type (and version) is this about?
IO one-by-one, lastest version.
I'm using Anki 24.04
#### Problem description

Hello. I've downloaded AnKing-Note-Types and installed IO one-by-one on Anki. However, when I try to create a new card, the specific buttons for this function do not appear. Everything is like for standart cards (see image below). How is it possible to fix it? 
![Capture d'écran 2024-04-17 232941](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/167363275/f20508dc-25ec-43d9-a0a8-87b2384c3351)
Thanks very much

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ X] I've restarted Anki to see if it helps
 - [X ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [X] I've tried to disable add-ons to see if there are any interactions present
 - [] My issue disappears when I hold shift while starting Anki.
 - [X] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?
Anki 24.04

#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
Windows 11

**Comment by AnKingMed** [comment]
You need the closet addon. See the instructions or watch this video

The AnKing Note Types and Add-on: https://youtu.be/NYUhNMyAZNs

**Comment by iuco2** [comment]
> You need the closet addon. See the instructions or watch this video
> 
> The AnKing Note Types and Add-on: https://youtu.be/NYUhNMyAZNs

Thanks for your answer. I have followed the instructions from Github / Youtube video and installed the add-on with the following AnkiWeb code (952691989) from the beggining... As you can see here, I've also imported the IO one-by-one function, which is the reason I don't understand why I cannot see the specific buttons to create new cards with this...
![Capture d'écran 2024-04-18 030159](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/167363275/0ebb6cc7-67d0-4474-95fc-2dff9de2256e)

**Comment by AnKingMed** [comment]
Did you install the closet add on?

**Comment by iuco2** [comment]
> Did you install the closet add on?
This one: https://ankiweb.net/shared/info/272311064 ? Yes.

**Comment by AnKingMed** [comment]
Yeah that one. Did you restart after installing? The buttons should appear when that is installed

**Comment by iuco2** [comment]
> Yeah that one. Did you restart after installing? The buttons should appear when that is installed

Yes, I restarted the program and followed the steps. It's very weird, but the problem persists as you can see here: 

![1](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/167363275/d43b675a-dc91-4479-9c89-de2e6f1101bd)

![2](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/167363275/ab1c83ad-5b05-4415-991b-ab1039dd20d9)

![3](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/167363275/8ed74343-4605-4cd2-abdd-ef3adc317367)

**Comment by AnKingMed** [comment]
Yeah that's weird. Maybe try downgrading to Anki 23.12.1

How to Upgrade and Downgrade Anki Version (or use multiple!): https://www.youtube.com/watch?v=4Bqs_SzUWGE&t=4s

**Comment by iuco2** [comment]
> Anki 23.12.1

Thanks for the advice. I just tried but this problem still persists...

**Comment by AnKingMed** [comment]
@abdnh @RisingOrange  im not sure what's going on. Any idea?

**Comment by abdnh** [comment]
These are the closet buttons:
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/41397710/295fd601-12e4-48ea-818d-123f9c5f52fc)

They are in your screenshot @iuco2

**Comment by iuco2** [comment]
> These are the closet buttons: ![image](https://private-user-images.githubusercontent.com/41397710/323551174-295fd601-12e4-48ea-818d-123f9c5f52fc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzczNDUsIm5iZiI6MTcxMzQzNzA0NSwicGF0aCI6Ii80MTM5NzcxMC8zMjM1NTExNzQtMjk1ZmQ2MDEtMTJlNC00OGVhLTgxOGQtMTIzZjljNWY1MmZjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDEwNDQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2OWJiZGRjMWE1NDIzNzFlODg4NGE4OGRkNjI3NTI0NmNjODZiZmUxNzlkYzFjOTc3YzM5M2NkYjQwMGI1ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PlfRkiTKghEwR34JzGvq6ZD0g04FUMRPW5DLWiIe0Dw)
> 
> They are in your screenshot @iuco2

Which one of the buttons below should I use to create an IO one-by-one card? 
![Capture d'écran 2024-04-18 134547](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/167363275/5bc7d64c-5355-4324-ac27-c1074dafbbba)

Also, I don't really understand why I cannot select a mask / image occlusion when I right click (see below).

![Capture d'écran 2024-04-18 135043](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/167363275/b4ab3cbd-b768-4e74-a420-31615d07a097)

**Comment by AnKingMed** [comment]
You have to click the small square within a square picture, not the dropdown.  The YouTube video I linked above shows how to do this
