### ISSUE TITLE
How can I have tags with full opacity always and not only when I hover over them.

### ISSUE THREAD

**Issue by CaptainDead** [AnKing-VIP/AnKing-Note-Types#180]
When we hover over the tags in the bottom they get darker, bolder. how can I make the tags to always be like that and not only when I hover over them? like if there is a change I can do in the 'cards' of my ranking note types then please tell me. I really need to know.

without hover - 
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139457914/2b171bd7-167d-4cac-a8b3-ef206b8cbd8e)

when hover - 
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/139457914/828000a1-54fb-41a2-8c69-686a5886a1e7)

**Comment by AnKingMed** [comment]
You would have to edit the styling css of the note type


```
/* Clickable Tags (need to download the add-on) */
kbd {
  display: inline-block;
  letter-spacing: .1px;
  font-weight: bold;
  font-size: 10px !important;
  text-shadow: none !important;
  padding: 0.05rem 0.1rem !important;
  margin: 1px !important;
  border-radius: 4px;
  border-width: 1.5px !important;
  border-style: solid;
  background-color: transparent !important;
  box-shadow: none !important;
  opacity: 1;
  vertical-align: middle !important;
  line-height: auto !important;
  height: auto !important;
}

/* Tag Becomes More Visible On Hover */
kbd:hover {
  opacity: 1;
  transition: opacity 0.2s ease;
}
```

**Comment by CaptainDead** [comment]
Thanks it worked💯🥂

I also found a way to change the BG color, I wanted to do that too.
