### ISSUE TITLE
OME Field always shows on mobile  (despite being disabled)

### ISSUE THREAD

**Issue by JChatara** [AnKing-VIP/AnKing-Note-Types#187]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*
Since the update to the anking notetype on 5-21, the OME field cannot be disabled on mobile ( it always shows up) despite being disabled and not present on desktop I cannot get it to go away on mobile

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
Version ⁨2.1.65 (aa9a734f)
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*

Windows 11

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```
none
```

**Comment by AnKingMed** [comment]
@abdnh would you mind looking into this?

**Comment by abdnh** [comment]
This is happening because the template has two separate buttons/banners for desktop and mobile. The simplest solution I see is to add a separate option for the mobile button.
