### ISSUE TITLE
Update alert always showing when I start Anki

### ISSUE THREAD

**Issue by justarmadillo** [AnKing-VIP/AnKing-Note-Types#193]
#### Which Note Type (and version) is this about?
Not specific to a note type
#### Problem description
each time I open Anki, I get this alert, And I have updated all of them multiple times, but the alert doesn't go away
![image](https://github.com/AnKing-VIP/AnKing-Note-Types/assets/10810222/4e754c48-1dc7-4e3a-a2b8-1591e0331a0b)

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
Version ⁨24.04.1 (ccd9ca1a)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Windows 11

```

```

**Comment by AnKingMed** [comment]
Can you delete the addon and redownload it?

**Comment by justarmadillo** [comment]
> Can you delete the addon and redownload it?

Already did it, same issue persists

**Comment by AnKingMed** [comment]
@abdnh @RisingOrange any ideas why this would be?

**Comment by abdnh** [comment]
I remember facing this sometimes. @justarmadillo Can you export your collection (without media) and upload it here? You will need to change the .colpkg extension to .zip to be able to upload it here.
