### ISSUE TITLE
Auto-collapsed personal notes tab and other tabs

### ISSUE THREAD

**Issue by jas2wf** [AnKing-VIP/AnKing-Note-Types#196]
#### Which Note Type (and version) is this about?

-this is about all notes in the anking dermki deck

#### Problem description

The "personal notes" section is auto-collapsed every time I do a card. This remains true despite whether the option to collapse is toggled or untoggled in the "fields" section. If possible, please fix this! I cant figure out how to do it. Thanks

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ x] I've restarted Anki to see if it helps
 - [ x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ x] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
 ⁨24.06.3 (d678e393)⁩
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)
windows 10

*Please include OS version as well if possible*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
You have to change the settings in the note styling.  The easiest way to do this is with the anking note types addon. There will be an anking menu and submenu for the note types.  Click the derm note type tab, then navigate to the checkbox to auto open that field. 

The AnKing Note Types and Add-on: https://youtu.be/NYUhNMyAZNs
