### ISSUE TITLE
IO-one-by-one doesn't work on Ankidroid independently

### ISSUE THREAD

**Issue by dhruvinpandya4** [AnKing-VIP/AnKing-Note-Types#200]
#### Which Note Type (and version) is this about?
IO-one-by-one, Its the latest version as updated by anking note types add on
#### Problem description
IO-one-by-one shows a blank card when used independently on ankidroid, i.e Whenever a new user who uses anki solely on ankidroid, imports a deck with IO-one-by-one cards, there is a blank screen. But when the cards are present in desktop use on PC (closet add on is installed), and then the user syncs to ankidroid, it works perfectly fine. What I seem the issue is that the closet.js file is not getting imported when you import the folder, but does get synced when you sync via anki servers. There is no way to confirm if the absence of this file is the cause of the issue as newer versions of ankidroid and android dont allow manual access to the android/data/com.ichi2.anki/collection.media folder where I could manually place the closet.js file to check if it starts working.

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x] I've restarted Anki to see if it helps
 - [x] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [x] I've tried to disable add-ons to see if there are any interactions present
 - [x] My issue disappears when I hold shift while starting Anki.
 - [x] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

```
24.06.2 Qt6 (Windows) + Ankidroid 2.18.4
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

Windows + Android

#### Error message (if any)

No error message, just a blank screen.

![WhatsApp Image 2023-12-31 at 00 45 49_78c0057c](https://github.com/user-attachments/assets/558cccc9-809f-42f1-9e59-d96508a98abf)

```

```

**Comment by AnKingMed** [comment]
@abdnh any idea how to resolve this? I think they're probably correct about the closet.js file

**Comment by dhruvinpandya4** [comment]
any updates? @abdnh

**Comment by abdnh** [comment]
It appears that Anki is failing to recognize the media reference in the template so it's not exporting the file. I'll look into a fix.

**Comment by dhruvinpandya4** [comment]
@abdnh the changes are made to the .ejs file, so how/when will these changes reflect in anki usage?

**Comment by abdnh** [comment]
The HTML was updated too: https://github.com/AnKing-VIP/AnKing-Note-Types/blob/master/Note%20Types/IO-one%20by%20one/Back%20Template.html

You can replace your back template with it to get the fix quickly.
