### ISSUE TITLE
Changing fields in Anking Note Types - doesn't update my cards?

### ISSUE THREAD

**Issue by wiffleman** [AnKing-VIP/AnKing-Note-Types#204]
#### Problem description

Trying to remove some of the extraneous, unused fields in the AnkingOverhaul note type. Have deselected them in the Note Types settings 

![image](https://github.com/user-attachments/assets/98e91663-0085-4c6b-a50f-11e7f2817abf)

However, my cards are still showing all of the fields in the edit mode.

Wondering what's going on? Thanks!

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ X] I've restarted Anki to see if it helps
 - [ X] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [X] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [X ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
This just disables them in the reviewing mode, not the edit mode. you can toggle them shut in the edit mode though

![CleanShot 2024-11-28 at 11 50 58@2x](https://github.com/user-attachments/assets/cd2ec87f-ce24-4026-b54c-2a2bbc449803)
