### ISSUE TITLE
Size difference when exporting Anking note type: Anki vs Ankidroid

### ISSUE THREAD

**Issue by NameLessGO** [AnKing-VIP/AnKing-Note-Types#205]
1. Make a sample deck with 1 card (Basic-Anking Note Type**) containing a high fidelity image ([3840×2160 – 1.3MB](https://samples-files.com/sample-jpg-file/))
1.1 [Basic-Anking.apkg.zip](https://github.com/user-attachments/files/17982433/Basic-Anking.apkg.zip)
3. Export the deck (Only Include Media is enabled) and sync
4. In another device, export the same deck and compare

Exporting with Anki default/built-in Basic Note type does not have the same problem

This bug report is crossposted from Anking repo to [Ankidroid](https://github.com/ankidroid/Anki-Android/issues/17536)

## Basic-Anking Comparison: Ankidroid vs Anki
![Image](https://github.com/user-attachments/assets/688f685e-1cc6-4597-aa21-d17b3c2fb50b)
Top file = Ankidroid
Bottom file = Anki

## Note Type Comparison: Basic-Anking vs Basic (Ankidroid)
![image](https://github.com/user-attachments/assets/0dadabf2-ed13-45a9-ace2-538014c20671)
Top File = Basic-Anking
Bottom File = Basic (Built-in)

## Debug Info
** Anking Note type version ``7d74b40``

Anki: ````Version ⁨24.11 (87ccd24e)⁩
Python 3.9.18 Qt 6.6.2 PyQt 6.6.1````

````AnkiDroid Version = 2.20alpha3 (0c5ea9d25ab1ac8fc0d18319578c87a7423c72af)

Backend Version = 0.1.48-anki24.11 (24.11 c47638ca36f99dd4f3b81ae82d964aec66e392e0)

Android Version = 14 (SDK 34)

ProductFlavor = play

Manufacturer = samsung

Model = SM-G991B```

Hardware = exynos2100

Webview User Agent = Mozilla/5.0 (Linux; Android 14; SM-G991B Build/UP1A.231005.007; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/132.0.6834.14 Mobile Safari/537.36

ACRA UUID = e05e35be-f57b-4474-a73a-ecded42040f8

FSRS = 1.4.3 (Enabled: true)

Crash Reports Enabled = true````

**Comment by AnKingMed** [comment]
@abdnh do you think this is on Ankidroids end or something specific to this note type?

**Comment by abdnh** [comment]
The difference is due to this option being enabled in AnkiDroid by default.
![image](https://github.com/user-attachments/assets/e054e79c-1c8b-4bba-875c-20017860d693)

To confirm, enable it and export on desktop and compare the size with the AnkiDroid export.

**Comment by NameLessGO** [comment]
Its a match
<img width="654" alt="image" src="https://github.com/user-attachments/assets/05ef8858-7b10-4ea7-82c6-f3c6bd31f319">

## Ankidroid Export Interface (Default options enabled)
![image](https://github.com/user-attachments/assets/a33472e5-24ea-43e2-aed6-741e42de1d9a)

## Anki Export Interface (Default options enabled)
<img width="654" alt="image" src="https://github.com/user-attachments/assets/2d52409f-49d2-4111-b345-4b22df7364b9">


To solve this, Should Ankidroid:
- Disable "Support older Anki version" by default", no export UI changes
- Disable "Support older Anki version" by default", and Adding option to enable/disable "Support older Anki versions"
- Match Anki Export Interface
  - Adding Support older Anki version (Disabled by default)
  - Disabling Include scheduling information by default
- Not a problem, won't fix it

**Comment by david-allison** [comment]
* **Match Anki Export Interface** 
    * https://github.com/ankidroid/Anki-Android/issues/17536

Thanks for the report & digging!
