### ISSUE TITLE
Image Occlusion cards do not flip automatically (mac)

### ISSUE THREAD

**Issue by Giovanni9665** [AnKing-VIP/AnKing-Note-Types#209]
# Bug Report: AnKing Add-on - Image Occlusion Issue

## Problem Description

When using the **Image Occlusion** feature with the following settings:

- **Reveal Mode:** Set to "Reveal One by One"
- **Flip Automatically:** Enabled

The following behaviour is observed:

https://github.com/user-attachments/assets/14958ea9-0ed1-4166-b6b1-a98ffb16cdee

- Despite the correct configuration, during review, the card's front side is displayed but does **not automatically flip** to reveal the image on the back as expected.
- The settings in both the **General** tab and the **Image Occlusion Options** tab have been reviewed and confirmed to be correctly configured.

---

## Operating System

**macOS** (latest version at the time of reporting)

**Comment by AnKingMed** [comment]
I believe the auto flip is for the "cloze one by one" feature, not the IO one by one. We could probably clarify this better so thanks for the report
