### ISSUE TITLE
Cannot zoom-in pictures with the Basic-type notes.

### ISSUE THREAD

**Issue by Farinata** [AnKing-VIP/AnKing-Note-Types#38]
Zooming-in pictures is not possible with the Basic-type notes.

**Comment by AnKingMed** [comment]
How are you trying to zoom? Which fields are the images in and are you doing hover or click?

**Comment by Farinata** [comment]
Zoom by clicking on the picture. 
Not working in all fields: front, back, personal notes, missing questions.
(For the cloze note types working well in all fields though).

**Comment by AnKingMed** [comment]
You're right. Looks like that part of the css got left out. I'll have to add that to my list of things to do

**Comment by abdnh** [comment]
Added to Basic-AnKingLanguage.
