### ISSUE TITLE
Clickable Tags v20 cannot work well with note type: IO one by one. I have to disable Clickable Tags v20 to use the note type

### ISSUE THREAD

**Issue by TrungLeMD** [AnKing-VIP/AnKing-Note-Types#71]
#### Problem description

*Please describe the issue concisely in here. In case of an error: Walk us through the steps you took to get there. What happened? What did you expect to happen?*

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [ ] I've restarted Anki to see if it helps
 - [ ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ ] I've tried to disable add-ons to see if there are any interactions present
 - [ ] My issue disappears when I hold shift while starting Anki.
 - [ ] I've checked if anyone else reported this problem before by looking through the issue reports. I also checked to see if there is a section about known issues in the add-on description, documentation, or README.
 

#### What Anki version are you using?

*Please open Anki, go to Help → About (windows) or Anki → About Anki (mac) to find the version. Edit the value between the backticks below

```
2.1.##
```
#### What Operating system are you using? (i.e. MacOS, Windows, Linux)

*Please include OS version as well if possible*

#### Error message (if any)

*If you've received an error message, please copy and paste it between the backticks below:*

```

```

**Comment by AnKingMed** [comment]
@damronatron do you have time to look into this and see if we need to modify anything? It's a pretty old report

**Comment by damronatron** [comment]
@AnKingMed yes

**Comment by hsyuen02** [comment]
I am experiencing the same problem with Clickable Tags v20 vs IO one by one. Similarly, I have to disable Clickable Tags v20. This issue is not resolved yet. Thank you for your attention.

**Comment by AnKingMed** [comment]
Can you describe what's happening?

**Comment by AnKingMed** [comment]
Is your note type up to date? I think we fixed this a while ago

**Comment by hsyuen02** [comment]
@AnKingMed I am not sure, I have reinstalled the add-on for the note type. How can I update it? :0
