### ISSUE TITLE
Some way to differentiate a normal cloze vs. one-by-one

### ISSUE THREAD

**Issue by BluMist** [AnKing-VIP/AnKing-Note-Types#92]
#### Which Note Type (and version) is this about?
AnKingOverhaul

#### Checklist

*Please replace the space inside the brackets with an **x** if the following items apply:*

 - [x ] I've verified that I use the latest version of the note type by redownloading it from AnkiWeb
 - [ x] I've checked if anyone else suggested this feature before by looking through the issue reports.

Currently there is no good visual indicator on the card to see whether a card has one-by-one enabled as far as I can tell. I sometimes hit the button expecting to see one-by-one but then all the clozes were revealed. A small icon/flag would be useful.

**Comment by AnKingMed** [comment]
What would you both propose is a good solution that is noticeable but not distracting? Make the cloze a different color?

**Comment by BluMist** [comment]
Color would be great if it is customizable (thinking color-blind)?

Another alternative (might not be simple to implement) would be just use a different bracket < > { } ( ) for the cloze?

**Comment by talkael** [comment]
color would be an easy solution
